---
x-build: &build
  build:
    context: "../"
    dockerfile: "development/Dockerfile"
    args:
      ALPINE_VERSION: "${ALPINE_VERSION:-3.14}"
      GO_VERSION: "${GO_VERSION:-1.21.5}"
      GORELEASER_VERSION: "${GORELEASER_VERSION:-0.18.1}"
      GOLANGCILINT_VERSION: "${GOLANGCILINT_VERSION:-1.51.2}"
  image: "josh-silvas/dmux-build:latest"

services:
  dmux-build:
    <<: *build
    env_file:
      - ".env"
    volumes:
      - "../:/workdir"
      - "./settings.ini:/root/.config/dmux/settings.ini"
    tty: true
