---
version: 2
project_name: "dmux"

release:
  github:
    owner: "josh-silvas"
    name: "dmux"
  name_template: "{{ .Tag }}"

brews:
  - name: "dmux"
    commit_author:
      name: "Josh Silvas"
      email: "josh@jsilvas.com"
    repository:
      owner: "josh-silvas"
      name: "dmux"
      branch: "main"
      token: "{{ .Env.GITHUB_TOKEN }}"
    directory: "Formula"
    url_template: "https://github.com/josh-silvas/dmux/releases/{{ .ProjectName }}/{{ .Tag }}/{{ .ArtifactName }}"
    caveats: |
      DMux v{{ .Tag }} Notes:
        1. DMux will create it's own system keychain called 'DMux-Keyring'
          1a. You may need to reauthenticate dmux to this keychain after update because the binary is
              a different signature.
        2. Release changelog located at:
          - https://github.com/josh-silvas/dmux/releases/tag/{{ .Tag }}
        3. For issues with this tool, please submit a GitHub issue here:
          - https://github.com/josh-silvas/dmux/issues
      v{{ .Tag }} NEW RELEASE INFO:
        4. Initial release!

    homepage: "https://github.com/josh-silvas/dmux"
    description: "DMux is a cli tool with ssh functionality for assist Network Engineering teams."
    skip_upload: "auto"
    test: "system '#{bin}/dmux'"
    install: "bin.install 'dmux'"

nfpms:
  - id: "dmux"
    file_name_template: "{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    builds:
      - "dmux-linux-amd64"
    vendor: "Josh Silvas"
    homepage: "https://github.com/josh-silvas/dmux"
    maintainer: "Josh Silvas <josh@jsilvas.com>"
    description: "DMux is a cli tool with ssh functionality for assist Network Engineering teams."
    license: "Apache 2.0"
    formats:
      - "deb"
    bindir: "/usr/local/bin"
    epoch: "1"

builds:
  - id: "dmux-osx-amd64"
    goos:
      - "darwin"
    targets:
      - "darwin_amd64"
    main: "cmd/main.go"
    ldflags: "-s -w -X main.buildVersion={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}"
    binary: "dmux"
    env:
      - "CGO_ENABLED=1"

  - id: "dmux-osx-arm64"
    goos:
      - "darwin"
    targets:
      - "darwin_arm64"
    main: "cmd/main.go"
    ldflags: "-s -w -X main.buildVersion={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}"
    binary: "dmux"
    env:
      - "CGO_ENABLED=1"

  - id: "dmux-linux-amd64"
    goos:
      - "linux"
    targets:
      - "linux_amd64"
    main: "cmd/main.go"
    ldflags: "-s -w -X main.buildVersion={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -linkmode external -extldflags -static"
    binary: "dmux"
    env:
      - "CC=x86_64-linux-musl-gcc"
      - "CXX=x86_64-linux-musl-g++"
      - "CGO_ENABLED=1"

  - id: "dmux-windows-amd64"
    goos:
      - "windows"
    targets:
      - "windows_amd64"
    main: "cmd/main.go"
    ldflags: "-s -w -X main.buildVersion={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}"
    binary: "dmux"
    env:
      - "CGO_ENABLED=1"

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: "tar.gz"
    files:
      - "LICENSE*"
      - "README*"
      - "CHANGELOG*"

checksum:
  name_template: "checksums.txt"

changelog:
  filters:
    exclude:
      - "^docs:"
      - "^test:"
  sort: "asc"

dist: "build"

env_files:
  github_token: "~/.config/goreleaser/github_com_token"
