---
project_name: "dmux"
builds:
  - id: "dmux-linux-amd64"
    targets:
      - "linux_amd64"
    main: "cmd/main.go"
    ldflags: "-s -w -X main.buildVersion={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -linkmode external -extldflags -static"
    binary: "dmux"
    env:
      - "CC=x86_64-linux-musl-gcc"
      - "CXX=x86_64-linux-musl-g++"
      - "CGO_ENABLED=1"

dist: "build-linux"

env_files:
  github_token: "~/.config/goreleaser/github_com_token"

github_urls:
  api: "https://github.com/api/v3/"
  upload: "https://github.com/api/uploads/"
  download: "https://github.com/"
