---
project_name: "nbot"

release:
  github:
    owner: "josh-silvas"
    name: "nbot"
  name_template: "{{ .Tag }}"

brews:
  - name: "nbot"
    commit_author:
      name: "Josh Silvas"
      email: "josh@jsilvas.com"
    tap:
      owner: "josh-silvas"
      name: "nbot"
    folder: "Formula"
    url_template: "https://github.com/josh-silvas/nbot/releases/{{ .ProjectName }}/{{ .Tag }}/{{ .ArtifactName }}"
    caveats: |
      NBot v{{ .Tag }} Notes:
        1. NBot will create it's own system keychain called 'NBot-Keyring'
          1a. You may need to reauthenticate nbot to this keychain after update because the binary is
              a different signature.
        2. Release changelog located at:
          - https://github.com/josh-silvas/nbot/releases/tag/{{ .Tag }}
        3. For issues with this tool, please submit a GitHub issue here:
          - https://github.com/josh-silvas/nbot/issues
      v{{ .Tag }} NEW RELEASE INFO:
        4. Initial release!

    homepage: "https://github.com/josh-silvas/nbot"
    description: "NBot is a Nautobot cli tool with ssh functionality for assist Network Engineering teams."
    skip_upload: "auto"
    test: "system '#{bin}/nbot'"
    install: "bin.install 'nbot'"

nfpms:
  - id: "nbot"
    file_name_template: "{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    builds:
      - "nbot-linux-amd64"
    replacements:
      amd64: "64-bit"
      386: "32-bit"
      darwin: "macOS"
      linux: "Linux"
    vendor: "Josh Silvas"
    homepage: "https://github.com/josh-silvas/nbot"
    maintainer: "Josh Silvas <josh@jsilvas.com>"
    description: "NBot is a Nautobot cli tool with ssh functionality for assist Network Engineering teams."
    license: "Apache 2.0"
    formats:
      - "deb"
    bindir: "/usr/local/bin"
    epoch: "1"

builds:
  - id: "nbot-osx-amd64"
    goos:
      - "darwin"
    targets:
      - "darwin_amd64"
    main: "cmd/main.go"
    ldflags: "-s -w -X main.buildVersion={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}"
    binary: "nbot"
    env:
      - "CGO_ENABLED=1"

  - id: "nbot-osx-arm64"
    goos:
      - "darwin"
    targets:
      - "darwin_arm64"
    main: "cmd/main.go"
    ldflags: "-s -w -X main.buildVersion={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}"
    binary: "nbot"
    env:
      - "CGO_ENABLED=1"

  - id: "nbot-linux-amd64"
    goos:
      - "linux"
    targets:
      - "linux_amd64"
    main: "cmd/main.go"
    ldflags: "-s -w -X main.buildVersion={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -linkmode external -extldflags -static"
    binary: "nbot"
    env:
      - "CC=x86_64-linux-musl-gcc"
      - "CXX=x86_64-linux-musl-g++"
      - "CGO_ENABLED=1"

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      386: "i386"
      amd64: "x86_64"
      darwin: "Darwin"
      linux: "Linux"
      windows: "Windows"
    format: "tar.gz"
    files:
      - "LICENSE*"
      - "README*"
      - "CHANGELOG*"

checksum:
  name_template: "checksums.txt"

changelog:
  filters:
    exclude:
      - "^docs:"
      - "^test:"
  sort: "asc"

dist: "build"

env_files:
  github_token: "~/.config/goreleaser/github_token"

github_urls:
  api: "https://github.com/api/v3/"
  upload: "https://github.com/api/uploads/"
  download: "https://github.com/"
