---
project_name: "dmux"
builds:
  - id: "dmux-osx-amd64"
    targets:
      - "darwin_amd64"
    main: "cmd/main.go"
    ldflags: "-s -w -X main.buildVersion={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}"
    binary: "dmux"
    env:
      - "CGO_ENABLED=1"

  - id: "dmux-osx-arm64"
    targets:
      - "darwin_arm64"
    main: "cmd/main.go"
    ldflags: "-s -w -X main.buildVersion={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}"
    binary: "dmux"
    env:
      - "CGO_ENABLED=1"

dist: "build"

env_files:
  github_token: "~/.config/goreleaser/github_com_token"

github_urls:
  api: "https://github.com/api/v3/"
  upload: "https://github.com/api/uploads/"
  download: "https://github.com/"
