---
# DMux CI goreleaser release workflow.
name: "Release"

concurrency:  # Cancel any existing runs of this workflow for this same PR
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - "*"

permissions:
  contents: "write"

jobs:

  tests:
    uses: "./.github/workflows/test.yml"

  goreleaser:
    runs-on: "ubuntu-latest"
    needs:
      - "tests"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
      - name: "Setup Golang"
        uses: "actions/setup-go@v4"
      - name: "Run GoReleaser"
        uses: "goreleaser/goreleaser-action@v5"
        with:
          # One of 'goreleaser' (default) or 'goreleaser-pro'
          distribution: "goreleaser"
          version: "1.23.0"
          args: "release --clean --rm-dist"
        env:
          GITHUB_TOKEN: "${{ secrets.AUTHENTICATION_TOKEN }}"
