# NBot CI testing workflow.
name: Tests

concurrency:  # Cancel any existing runs of this workflow for this same PR
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true

# This GitHub action runs your tests for each pull request and push.
on:
  pull_request:
    paths-ignore:
      - "README.md"
      - "develop/README.md"
  push:
    paths-ignore:
      - "README.md"
      - "develop/README.md"

# Testing only needs permissions to read the repository contents.
permissions:
  contents: "read"

jobs:
  # Ensure project builds before running testing matrix
  golangci-lint:
    name: "Build"
    runs-on: "ubuntu-latest"
    timeout-minutes: 5
    steps:
      - uses: "actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9" # v3.5.3
      - uses: "actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe" # v4.1.0
        with:
          go-version-file: "go.mod"
          cache: true

      - name: "Run GolangCI Linting Process"
        run: "make _lint"

  # Run unit tests
  test:
    name: "NBot Unit Tests"
    needs:
      - "golangci-lint"
    runs-on: "ubuntu-latest"
    timeout-minutes: 15
    strategy:
      fail-fast: false
    steps:
      - uses: "actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9" # v3.5.3
      - uses: "actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe" # v4.1.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: "Run Unit Tests"
        run: "make _unittest"
        timeout-minutes: 10
